# Generated by Django 2.2.16 on 2023-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/picture.jpg', help_text='Загрузите фото профиля', null=True, upload_to='users/', verbose_name='Фото профиля'),
        ),
    ]
